// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_services.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createDriverService = `-- name: CreateDriverService :one
INSERT INTO driver_services (
    driver_id,
    service_id,
    status
) VALUES (
    $1, $2, $3
) RETURNING id, driver_id, service_id, status, approved_at, approved_by, created_at, updated_at, deleted_at
`

type CreateDriverServiceParams struct {
	DriverID  uuid.UUID           `json:"driver_id"`
	ServiceID uuid.UUID           `json:"service_id"`
	Status    DriverServiceStatus `json:"status"`
}

func (q *Queries) CreateDriverService(ctx context.Context, arg CreateDriverServiceParams) (DriverService, error) {
	row := q.db.QueryRow(ctx, createDriverService, arg.DriverID, arg.ServiceID, arg.Status)
	var i DriverService
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.ServiceID,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverServicesByDriverID = `-- name: GetDriverServicesByDriverID :many
SELECT id, driver_id, service_id, status, approved_at, approved_by, created_at, updated_at, deleted_at
FROM driver_services
WHERE driver_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDriverServicesByDriverID(ctx context.Context, driverID uuid.UUID) ([]DriverService, error) {
	rows, err := q.db.Query(ctx, getDriverServicesByDriverID, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverService{}
	for rows.Next() {
		var i DriverService
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.ServiceID,
			&i.Status,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
