root = "."
tmp_dir = "cmd/tmp"

[build]
  cmd = "go build -tags=dev -gcflags='all=-N -l' -trimpath -o cmd/tmp/app cmd/server/main.go"
  bin = "cmd/tmp/app"
  delay = 200
  poll = false
  send_interrupt = true
  kill_delay = 500

  include_ext = ["go"]

  exclude_dir = [
    "cmd/tmp",
    "vendor",
    "docs",
    "docs-api",
    "docs-internal",
    "node_modules",
    "storage",
    "migrations",
    ".git"
  ]

[log]
  time = true

[misc]
  clean_on_exit = true