// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: surcharge_conditions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurchargeCondition = `-- name: CreateSurchargeCondition :one
INSERT INTO system_surcharge_conditions (code, name, condition_type, config, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, condition_type, config, is_active, name
`

type CreateSurchargeConditionParams struct {
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	ConditionType string      `json:"condition_type"`
	Config        []byte      `json:"config"`
	IsActive      pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateSurchargeCondition(ctx context.Context, arg CreateSurchargeConditionParams) (SystemSurchargeCondition, error) {
	row := q.db.QueryRow(ctx, createSurchargeCondition,
		arg.Code,
		arg.Name,
		arg.ConditionType,
		arg.Config,
		arg.IsActive,
	)
	var i SystemSurchargeCondition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ConditionType,
		&i.Config,
		&i.IsActive,
		&i.Name,
	)
	return i, err
}

const deleteSurchargeCondition = `-- name: DeleteSurchargeCondition :exec
DELETE FROM system_surcharge_conditions
WHERE id = $1
`

func (q *Queries) DeleteSurchargeCondition(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurchargeCondition, id)
	return err
}

const getSurchargeConditionByCode = `-- name: GetSurchargeConditionByCode :one
SELECT id, code, condition_type, config, is_active, name FROM system_surcharge_conditions
WHERE code = $1
`

func (q *Queries) GetSurchargeConditionByCode(ctx context.Context, code string) (SystemSurchargeCondition, error) {
	row := q.db.QueryRow(ctx, getSurchargeConditionByCode, code)
	var i SystemSurchargeCondition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ConditionType,
		&i.Config,
		&i.IsActive,
		&i.Name,
	)
	return i, err
}

const getSurchargeConditionByID = `-- name: GetSurchargeConditionByID :one
SELECT id, code, condition_type, config, is_active, name FROM system_surcharge_conditions
WHERE id = $1
`

func (q *Queries) GetSurchargeConditionByID(ctx context.Context, id uuid.UUID) (SystemSurchargeCondition, error) {
	row := q.db.QueryRow(ctx, getSurchargeConditionByID, id)
	var i SystemSurchargeCondition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ConditionType,
		&i.Config,
		&i.IsActive,
		&i.Name,
	)
	return i, err
}

const listSurchargeConditions = `-- name: ListSurchargeConditions :many
SELECT id, code, condition_type, config, is_active, name FROM system_surcharge_conditions
ORDER BY code ASC
`

func (q *Queries) ListSurchargeConditions(ctx context.Context) ([]SystemSurchargeCondition, error) {
	rows, err := q.db.Query(ctx, listSurchargeConditions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSurchargeCondition{}
	for rows.Next() {
		var i SystemSurchargeCondition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ConditionType,
			&i.Config,
			&i.IsActive,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurchargeCondition = `-- name: UpdateSurchargeCondition :one
UPDATE system_surcharge_conditions
SET
  code = $2,
  name = $3,
  condition_type = $4,
  config = $5,
  is_active = $6
WHERE id = $1
RETURNING id, code, condition_type, config, is_active, name
`

type UpdateSurchargeConditionParams struct {
	ID            uuid.UUID   `json:"id"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	ConditionType string      `json:"condition_type"`
	Config        []byte      `json:"config"`
	IsActive      pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateSurchargeCondition(ctx context.Context, arg UpdateSurchargeConditionParams) (SystemSurchargeCondition, error) {
	row := q.db.QueryRow(ctx, updateSurchargeCondition,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.ConditionType,
		arg.Config,
		arg.IsActive,
	)
	var i SystemSurchargeCondition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ConditionType,
		&i.Config,
		&i.IsActive,
		&i.Name,
	)
	return i, err
}
