// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: surcharge_rule_conditions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteSurchargeRuleConditionsBySurchargeID = `-- name: DeleteSurchargeRuleConditionsBySurchargeID :exec
DELETE FROM system_surcharge_rule_conditions
WHERE surcharge_id = $1
`

func (q *Queries) DeleteSurchargeRuleConditionsBySurchargeID(ctx context.Context, surchargeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurchargeRuleConditionsBySurchargeID, surchargeID)
	return err
}

const getConditionIDsBySurchargeID = `-- name: GetConditionIDsBySurchargeID :many
SELECT condition_id
FROM system_surcharge_rule_conditions
WHERE surcharge_id = $1
`

func (q *Queries) GetConditionIDsBySurchargeID(ctx context.Context, surchargeID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getConditionIDsBySurchargeID, surchargeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var condition_id uuid.UUID
		if err := rows.Scan(&condition_id); err != nil {
			return nil, err
		}
		items = append(items, condition_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSurchargeRuleCondition = `-- name: InsertSurchargeRuleCondition :exec
INSERT INTO system_surcharge_rule_conditions (surcharge_id, condition_id)
VALUES ($1, $2)
`

type InsertSurchargeRuleConditionParams struct {
	SurchargeID uuid.UUID `json:"surcharge_id"`
	ConditionID uuid.UUID `json:"condition_id"`
}

func (q *Queries) InsertSurchargeRuleCondition(ctx context.Context, arg InsertSurchargeRuleConditionParams) error {
	_, err := q.db.Exec(ctx, insertSurchargeRuleCondition, arg.SurchargeID, arg.ConditionID)
	return err
}
